{
 "title": "CoreDNS",
 "description": "A dashboard for CoreDNS",
 "tags": [
  "dns",
  "coredns"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "10s,30s,1m,2m,5m,10m,1h" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(coredns_build_info,instance)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(coredns_dns_requests_total{instance=~\"$instance\"},server)"
    }
   },
   {
    "name": "zone",
    "label": "Zone",
    "query": {
     "query": "label_values(coredns_dns_requests_total{instance=~\"$instance\", server=~\"$server\"},zone)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CoreDNS Instances",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "coredns_build_info{instance=~\"$instance\"} ",
     "legendFormat": "{{version}}"
    },
    {
     "expr": "sum(coredns_plugin_enabled{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(coredns_dns_request_duration_seconds_bucket{instance=~\"$instance\", server=~\"$server\"}[$interval])) by (le))\r\n",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Total External Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coredns_dns_requests_total{instance=~\"$instance\", server=~\"$server\", zone=~\".\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Guarded Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coredns_guard_request_match_total{instance=~\"$instance\", server=~\"$server\"}) / sum(coredns_dns_requests_total{instance=~\"$instance\", server=~\"$server\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_alloc_bytes{instance=~\"$instance\", server=~\"$server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{instance=~\"$instance\", server=~\"$server\"}[$interval])) * 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Total Requests per Zone",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(4, sum(coredns_dns_requests_total{instance=~\"$instance\", server=~\"$server\"}) by (zone))",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "Total Failed Requests",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coredns_dns_responses_total{instance=~\"$instance\", server=~\"$server\", rcode=\"SERVFAIL\", zone=~\"$zone\"})",
     "legendFormat": "servfail"
    },
    {
     "expr": "sum(coredns_dns_responses_total{instance=~\"$instance\", server=~\"$server\", rcode=\"REFUSED\", zone=~\"$zone\"})",
     "legendFormat": "refused"
    },
    {
     "expr": "sum(coredns_dns_responses_total{instance=~\"$instance\", server=~\"$server\", rcode=\"NXDOMAIN\", zone=~\"$zone\"})",
     "legendFormat": "nxdomain"
    }
   ]
  },
  {
   "title": "Total Guarded Requests",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coredns_guard_request_match_total{instance=~\"$instance\", server=~\"$server\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Total Cache Responses",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coredns_redisc_hits_total{instance=~\"$instance\", server=~\"$server\"})",
     "legendFormat": "redis: hits"
    },
    {
     "expr": "sum(coredns_redisc_misses_total{instance=~\"$instance\", server=~\"$server\"})",
     "legendFormat": "redis: misses"
    },
    {
     "expr": "sum(coredns_redisc_set_errors_total{instance=~\"$instance\", server=~\"$server\"})",
     "legendFormat": "redis: errors"
    },
    {
     "expr": "sum(coredns_redisc_drops_total{instance=~\"$instance\", server=~\"$server\"})",
     "legendFormat": "redis: drops"
    },
    {
     "expr": "sum(coredns_cache_entries{instance=~\"$instance\", zones=~\"$zone\", server=~\"$server\"}) by (type)",
     "legendFormat": "local: {{type}}"
    }
   ]
  },
  {
   "title": "Requests by Server over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{instance=~\"$instance\", server=~\"$server\", zone=~\"$zone\"}[$interval])) by (server)",
     "legendFormat": "{{server}}"
    },
    {
     "expr": "sum(rate(coredns_cache_requests_total{instance=~\"$instance\", server=~\"$server\", zone=~\"$zone\"}[$interval]))",
     "legendFormat": "cache"
    }
   ]
  },
  {
   "title": "Responds by Plugin over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_responses_total{instance=~\"$instance\", server=~\"$server\", zone=~\"$zone\", plugin=\"cache\", rcode!=\"NXDOMAIN\"}[$interval]))",
     "legendFormat": "cache"
    },
    {
     "expr": "sum(rate(coredns_dns_responses_total{instance=~\"$instance\", server=~\"$server\", zone=~\"$zone\", plugin=\"\"}[$interval])) ",
     "legendFormat": "undefined"
    },
    {
     "expr": "sum(rate(coredns_dns_responses_total{instance=~\"$instance\", server=~\"$server\", plugin=\"forward\"}[$interval]))",
     "legendFormat": "forward"
    },
    {
     "expr": "sum(rate(coredns_dns_responses_total{instance=~\"$instance\", server=~\"$server\", rcode=\"SERVFAIL\"}[$interval]))",
     "legendFormat": "error"
    },
    {
     "expr": "sum(rate(coredns_dns_responses_total{instance=~\"$instance\", server=~\"$server\", plugin=\"auto\"}[$interval]))",
     "legendFormat": "auto"
    },
    {
     "expr": "sum(rate(coredns_dns_responses_total{instance=~\"$instance\", server=~\"$server\", plugin=\"file\"}[$interval]))",
     "legendFormat": "file"
    }
   ]
  },
  {
   "title": "Requests by Zone over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{instance=~\"$instance\", server=~\"$server\", zone=~\"$zone\"}[$interval])) by (zone)",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "Requests by Type over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{instance=~\"$instance\", server=~\"$server\", zone=~\"$zone\"}[$interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Response Size in Bytes over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_responses_total{instance=~\"$instance\", server=~\"$server\", zone=~\"$zone\"}[$interval])) by (rcode)",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "title": "Response Latency over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(coredns_dns_request_duration_seconds_bucket{instance=~\"$instance\", server=~\"$server\", zone=~\"${zone:raw}\"}[$interval])) by (le))\r\n",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_duration_seconds_bucket{instance=~\"$instance\", server=~\"$server\", zone=~\"${zone:raw}\"}[$interval])) by (le))\r\n",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_duration_seconds_bucket{instance=~\"$instance\", server=~\"$server\", zone=~\"${zone:raw}\"}[$interval])) by (le))\r\n",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Total Responses by Type",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(4, sum(coredns_dns_requests_total{instance=~\"$instance\", server=~\"$server\", zone=~\"$zone\"}) by (type))",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "title": "Total Responses by Code",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(4, sum(coredns_dns_responses_total{instance=~\"$instance\", server=~\"$server\", zone=~\"$zone\"}) by (rcode))",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "title": "Cache Hitrate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{instance=~\"$instance\", server=~\"$server\", zone=~\"$zone\", type=\"success\"}[$interval])) / sum(rate(coredns_cache_requests_total{instance=~\"$instance\", server=~\"$server\", zone=~\"$zone\"}[$interval]))",
     "legendFormat": "success"
    },
    {
     "expr": "sum(rate(coredns_cache_hits_total{instance=~\"$instance\", server=~\"$server\", zone=~\"$zone\", type=\"denial\"}[$interval])) / sum(rate(coredns_cache_requests_total{instance=~\"$instance\", server=~\"$server\", zone=~\"$zone\"}[$interval]))",
     "legendFormat": "denial"
    },
    {
     "expr": "(sum(rate(coredns_cache_requests_total{instance=~\"$instance\", server=~\"$server\", zone=~\"$zone\"}[$interval])) - sum(rate(coredns_cache_hits_total{instance=~\"$instance\", server=~\"$server\", type=\"success\", zone=~\"$zone\"}[$interval]))) / sum(rate(coredns_cache_requests_total{instance=~\"$instance\", server=~\"$server\", zone=~\"$zone\"}[$interval]))",
     "legendFormat": "misses"
    }
   ]
  }
 ]
}